version: '3.7' # スキーマバージョンの定義

services:
    app: # この名前が自動的にネットワークのエイリアスとなる
        image: node:12-alpine
        command: sh -c "apk add --no-cache python2 g++ make && yarn install && yarn run dev"
        ports:
            - 3011:3011
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos
    mysql:
        image: mysql:5.7
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos
volumes:
    todo-mysql-data: # docker run コマンドと違いボリュームの作成をここで記述する必要がある

# ネットワーク設定は指定しないと自動的にアプリケーションスタックに指定したネットワークを作成する(今回だと app_default という命名)
